-- create database ricette;
-- GRANT ALL PRIVILEGES ON DATABASE restaurantservice TO 'postgres'@'%' WITH GRANT OPTION;
-- CREATE TABLE ricette( id serial not null, autore varchar (255), titolo varchar (255), preparazione varchar (255));
